name: Video Generation Script

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: "0 */4 * * *"  # Runs every 4 hours (6 times a day)

jobs:
  run_script:
    runs-on: ubuntu-latest  # Free GitHub-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetches repository files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use a compatible version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install any required packages
          pip install python-dotenv        # Load environment variables from .env (if needed)

      - name: Inject API Keys
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}  # Load from GitHub Secrets
        run: python main.py  # Replace with your script filename

      - name: Upload Generated Audio Files (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: audio-files
          path: temp_audio/  # Uploads generated MP3 files
